In [1]:
import numpy as np

In [3]:

import numpy as np
a = np.array([1,2])
b = np.array([9,40])
out = np.log(a)
print(out)
out = np.exp(a)
print(out)
out = a.dot(b)
print(out)

[0.         0.69314718]
[2.71828183 7.3890561 ]
89


In [8]:

out = np.linalg.norm(a)    
print(out)
out = np.linalg.norm(b)
print(out)
out = np.linalg.norm(np.dot(a,b))
print(out)

101.90682018393078
41.0


ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
# matrix
a = np.matrix([[1,2,3],[49,59,67]])
print(a)
print(a[0,1])  #print given index
x = np.array(a)
print(x)
print(x.T)     #transpose of a matrix
m = np.zeros((2,2))
print(m)
m = np.zeros((2,2,3))
print(m)
n = np.ones((3,5))
print(n)

z = np.random.random((3,3))
print(z)

[[ 1  2  3]
 [49 59 67]]
2
[[ 1  2  3]
 [49 59 67]]
[[ 1 49]
 [ 2 59]
 [ 3 67]]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.37259006 0.80753536 0.32695762]
 [0.83291716 0.25327755 0.50539787]
 [0.96415723 0.93690808 0.78773984]]


In [9]:
print(np.random.randn(2,2) )  


[[-1.05876247 -0.11877896]
 [ 1.51917499  1.41079059]]


In [10]:
p = np.array([[12,2],[3,4]])
q = np.array([[3,4],[5,6]])
i = np.linalg.inv(p)
print(i)

d = np.linalg.det(q)
print(d)
di = np.diag(p)
x = np.diag([1,2,3,4])
print(x)
x = np.trace(x)
print(x)

[[-2.   1. ]
 [ 1.5 -0.5]]
-1.9999999999999971
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
10
